name: Release

on:
  push:
    tags:
      - "*"

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build extension package
        run: pnpm zip

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          version="${tag#v}"
          
          gh release create "$tag" \
                  --title="$tag" \
                  --generate-notes \
                  ".output/awesome-toc-${version}-chrome.zip"
